#!/bin/bash

if [ $1 = "f" ]; then
        cat ~/Documents/commands | grep --color=always $2
fi

if [ $1 = "a" ]; then
        echo $2 >> ~/Documents/commands
fi

if [ $1 = "l" ]; then
        cat ~/Documents/commands
fi
